http://127.0.0.1:80/api/v0/insert?rid=8167293698&name=ADaDadas&ip=1.1.1.1

################################

http://127.0.0.1:80//api/v1/user/8167293698


################################

http://127.0.0.1:80/api/v1/user/exist/8167293698


################################

http://127.0.0.1:80/api/v0/user/8167293698

################################

https://socialclub.rockstargames.com/member/xeneht